const INGREDIENTS = [
  "Absinthe",
  "Aperol",
  "Apricot brandy",
  "Blackberry liqueur",
  "Cachaca",
  "Campari",
  "Champagne",
  "Cherry liqueur",
  "Coconut milk",
  "Coffee liqueur",
  "Cognac",
  "Cola",
  "Cranberry juice",
  "Cream",
  "Cream liqueur",
  "Créme liqueur",
  "DOM Bénédictine",
  "Dark rum",
  "DiSaronno",
  "Drambuie",
  "Dry White Wine",
  "Egg yolk",
  "Galliano",
  "Gin",
  "Ginger Ale",
  "Ginger beer",
  "Grapefruit juice",
  "Hot coffee",
  "Kirsch",
  "Lemon juice",
  "Lillet Blonde",
  "Lime juice",
  "Olive juice",
  "Orange Bitters",
  "Orange juice",
  "Peach puree",
  "Peach schnapps",
  "Pineapple juice",
  "Pisco",
  "Prosecco",
  "Raspberry liqueur",
  "Red Port",
  "Soda water",
  "Syrup",
  "Tequila",
  "Tomato juice",
  "Triple Sec",
  "Vermouth",
  "Vodka",
  "Whiskey",
  "White rum",
];
